[files]
extend-exclude = [
    "tests/data/",
]

[default.extend-words]
# error: `connectio` should be `connection`
#   --> .\tests\test_dumps.py:66:33
#    |
# 66 |                 "Path 'database.connectio' specified in"
#    |                                 ^^^^^^^^^
# error: `connectio` should be `connection`
#   --> .\tests\test_dumps.py:69:42
#    |
# 69 |             {"inline_tables": {"database.connectio"}},
#    |                                          ^^^^^^^^^
connectio = "connectio"
