[global]
respect-gitignore = true
disable = [
    "MD013",
    "MD029",
    "MD033",
    "MD036",
    "MD041",
]
include = [
    "README.md",
    "benchmark/README.md"
]
exclude = [
    ".git",
    ".github",
    "dist",
    "build",
    "CHANGELOG.md",
    "LICENSE.md",
]
