name: CI

permissions: { }

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  linux:
    name: "linux (${{ matrix.platform.runner }} / ${{ matrix.platform.target }})"
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - {
            runner: ubuntu-latest,
            target: x86_64,
            interpreter: "3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.11",
            maturin-args: "--release --out dist"
          }
          - {
            runner: ubuntu-latest,
            target: x86,
            interpreter: "3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.11",
            maturin-args: "--release --out dist"
          }
          - {
            runner: ubuntu-latest,
            target: aarch64,
            interpreter: "3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.11",
            maturin-args: "--release --out dist --zig"
          }
          - {
            runner: ubuntu-latest,
            target: armv7,
            interpreter: "3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.11",
            maturin-args: "--release --out dist --zig"
          }
          - {
            runner: ubuntu-latest,
            target: s390x,
            interpreter: "3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.11",
            maturin-args: "--release --out dist --no-default-features"
          }
          - {
            runner: ubuntu-latest,
            target: ppc64le,
            interpreter: "3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.11",
            maturin-args: "--release --out dist --no-default-features"
          }
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.x
      - name: Install libatomic for ARMv7
        if: matrix.platform.target == 'armv7'
        run: |
          sudo apt-get update 
          sudo apt-get install -y libatomic1
      - name: "Build wheels"
        uses: PyO3/maturin-action@86b9d133d34bc1b40018696f782949dac11bd380 # v1.49.4
        with:
          target: ${{ matrix.platform.target }}
          args: ${{ matrix.platform.maturin-args }} --interpreter ${{ matrix.platform.interpreter }}
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }} # zizmor: ignore[cache-poisoning]
          manylinux: auto
      - name: "Upload wheels"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: wheels-linux-${{ matrix.platform.target }}
          path: dist
